version: '2.1'

services:

  # homebridge-knx
  homebridge-knx:
    #env_file: .env
    image: spanghf37/homebridge-knx:amd64
    restart: always
    network_mode: host
    healthcheck:
      test: "curl -f http://localhost:18081"
      interval: 5s
      timeout: 5s
      retries: 20
    restart: always
    volumes:
      - /home/docker/homebridge/:/root/.homebridge/
    depends_on:
      knxd:
        condition: service_healthy
      #redis:
        #condition: service_healthy
  knxd:
    #env_file: .env
    image: spanghf37/knxd:amd64
    restart: always
    #build: .
    network_mode: host
    volumes:
      # mount docker volumes persistant inside docker container
      - /home/docker/knxd/:/etc/knxd/
    #links:
      # Link to MYSQL DB (see below)
      #- db
      #- redis
    healthcheck:
      test: "/home/docker-healthcheck"
      interval: 5s
      retries: 10
    #depends_on:
      #db:
        #condition: service_healthy
      #redis:
        #condition: service_healthy
#redis:
    # Official redis image
    #image: amd64/redis:latest
    #env_file:
    #  - '.env'
    #healthcheck:
    #  test: ["CMD", "redis-cli","ping"]
    #  interval: 5s
    #  retries: 10
    #restart: always
    #volumes:
    #  - /mnt/data/configs/emoncms/emon-redis-data:/data

volumes:
  knxd:
  homebridge:
  #emon-redis-data:
